name: Get Closed Issues

on:
  workflow_dispatch:

jobs:
  get-closed-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Get closed issues in the past 30 days
        run: |
          curl -H "Accept: application/vnd.github+json" \
            "https://api.github.com/search/issues?q=repo:regnaer/TestingWorkflows+is:issue+state:closed+closed:>$(date -d '-30 days' +%Y-%m-%d)"
