name: Update Sub-Issues Sprint Field

on:
  issue_comment:
    types: [created]

jobs:
  update-tasks:
    if: github.event.comment.body == 'update tasks'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Get parent issue details
        id: get-parent-issue
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} > parent_issue.json
          echo "SPRINT_FIELD=$(jq -r '.fields.customfield_PVTIF_lAHOAYT8e84A0x6mzgqW4r0' parent_issue.json)" >> $GITHUB_ENV

      - name: Get all open sub-issues
        id: get-sub-issues
        run: |
          SUB_ISSUES=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open&labels=sub-issue")
          echo "SUB_ISSUES=$SUB_ISSUES" >> $GITHUB_ENV

      - name: Update sub-issues' Sprint field
        run: |
          for issue in $(echo $SUB_ISSUES | jq -r '.[] | @base64'); do
            _jq() {
              echo ${issue} | base64 --decode | jq -r ${1}
            }
            ISSUE_NUMBER=$(_jq '.number')
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              -d '{"query": "mutation { updateProjectV2ItemFieldValue( input: {projectId: \"${{ secrets.PROJECT_ID }}\", itemId: \"${ISSUE_NUMBER}\", fieldId: \"PVTIF_lAHOAYT8e84A0x6mzgqW4r0\", value: \"${{ env.SPRINT_FIELD }}\" }) { projectV2Item { id } } }"}' \
              https://api.github.com/graphql
          done
